### ISSUE TITLE
Add support for meta data querying through the Prometheus API

### ISSUE THREAD

**Issue by mgoeminne** [cetic/tsorage#85]
In order to extend the support of [the Prometheus API](https://prometheus.io/docs/prometheus/latest/querying/api/), meta data querying should be supported.

- [ ] Getting time series corresponding to a tagset.
- [x] Getting used tag names, over the entire dataset. 
- [x] Querying the tag values, corresponding to a given tag name, over the entire dataset.
- [x] Parse PromQL.
- [x] Evaluate PromQL expressions.

**Comment by mgoeminne** [comment]
An early support for PromQL is provided.

Instant vector expressions, range vector expressions, and scalar expressions are supported.

Time series listing, label listening and selector extractions are supported as well.

Expressions are parsed by using Parser Combinators. Parsed expressions are evaluated using arbitrary engines. A Casssandra engine is implemented. 

However, this support is at an early stage. Some PromQL features (for instance, some aggregation functions) are not yet available.
